# Generated by Django 6.0.5 on 2026-05-30 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_exercise_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='image_url',
        ),
    ]
