# Generated by Django 6.0.5 on 2026-05-31 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_exercise_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutlog',
            name='routine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.routine'),
        ),
    ]
